[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
vt = 1

[default_session]
command = "tuigreet --cmd Hyprland --theme border=magenta;text=cyan;prompt=green;time=red;action=blue;button=yellow;container=black;input=red"
user = "greeter"

[initial_session]
command = "Hyprland"
user = "miro"
