- 1.1.11
- _NAME: MX Vertical Wireless Mouse
  _absent: [hi-res-scroll, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert, thumb-scroll-mode,
    onboard_profiles, report_rate, report_rate_extended, pointer_speed, speed-change, backlight, backlight_level, backlight_duration_hands_out, backlight_duration_hands_in,
    backlight_duration_powered, backlight-timed, led_control, led_zone_, fn-swap, disable-keyboard-keys, crown-smooth, divert-crown, divert-gkeys, m-key-leds,
    mr-key-led, multiplatform, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer, adc_power_management]
  _battery: 4096
  _dpi-sliding: 0x9
  _modelId: B020407BC08A
  _sensitive: {change-host: false, divert-keys: false, dpi: false, dpi-sliding: false, lowres-scroll-mode: false, lowres-smooth-scroll: true, mouse-gestures: false,
    reprogrammable-keys: false}
  _serial: 0987B4DB
  _unitId: AA8453FB
  _wpid: 407B
  change-host: null
  divert-keys: {0x0: 0x2, 0x52: 0x0, 0x53: 0x0, 0x56: 0x0, 0xfd: 0x0}
  dpi: '1500'
  lowres-scroll-mode: false
  lowres-smooth-scroll: false
  persistent-remappable-keys: null
  reprogrammable-keys: {0x50: 0x50, 0x51: 0x51, 0x52: 0x52, 0x53: 0x53, 0x56: 0x56, 0xfd: 0xfd}
