#{{{ ## RULES
# windowrule v1 syntax is gone. windowrule now behaves like windowrule, deprecating the windowrule keyword
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# move
windowrule = workspace 3, match:initial_class ^(vifm)$
windowrule = workspace 9, match:initial_class ^(top)$
windowrule = workspace 5 silent, match:initial_class ^(audio)$

windowrule = float on, center on, match:class file-roller

# windowrule = float,class:SpeedCrunch
# windowrule = center,class:SpeedCrunch
# windowrule = size 500 500,class:SpeedCrunch

windowrule = fullscreen on, match:class mpv
windowrule = float on, opacity 1.0 0.1, match:class ^(KeePassXC)$
windowrule = center on, size 1100 600, match:class KeePassXC

windowrule = float on, match:title ^(pavucontrol)$
windowrule = center on, match:class ^(pavucontrol|org.pulseaudio.pavucontrol|com.saivert.pwvucontrol)$
windowrule = float on, match:title ^(blueman-manager)$
windowrule = float on, match:title ^(nm-connection-editor)$

windowrule = float on, match:class zenity
windowrule = float on, match:class ^([Yy]ad)$
windowrule = float on, match:class ^([Qq]alculate-gtk)$
windowrule = float on, match:class menu

# scratchpads 
# workspace = special:special, gapsout:30
windowrule = workspace special:drop, float on, size (monitor_w*0.9) (monitor_h*0.7), move ((monitor_w*0.05)) (50), match:class ^(drop)$
windowrule = workspace special:chat, float on, size 900 600, match:class ^(chat)$
windowrule = workspace special:news, float on, size 900 800, match:class ^(news)$

windowrule = float on, pin on, center on, size 1100 150, match:class rsvp

windowrule = float on, match:class cheatsh
windowrule = float on, match:class read

windowrule = float on, center on, size 1000 (monitor_h*0.9), match:class task

windowrule = float on, center on, size 1000 (monitor_h*0.9), match:class music

windowrule = float on, center on, size 500 150, match:class audio

windowrule = float on, center on, size 700 (monitor_h*0.9), match:class trash

windowrule = float on, center on, size 700 400, match:class qb

windowrule = float on, center on, size 1000 900, match:class ytfzf

windowrule = float on, pin on, size 380 210, move ((monitor_w*1)-383) ((monitor_h*1)-230), rounding 0, match:class videopopup

# windowrule = noborder,class:videopopup
# windowrule = nofocus,class:videopopup

windowrule = float on, match:class application.Main
windowrule = float on, match:class ovh.miroslaw.timefx.TimeFX

## layer
layerrule = blur on, ignore_alpha 0, order -3, match:namespace notifications
# Rofi
layerrule = blur on, ignore_alpha 0, dim_around on, animation popin 85%, match:namespace rofi
# layerrule = noanim, namespace:rofi
# Ignore maximize requests from apps. You'll probably like this.
# windowrule = suppressevent maximize, class:.*
# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0

# Dialog windows – float+center these windows.
windowrule = center on, float on, match:title ^(Open File)(.*)$
windowrule = center on, float on, match:title ^(Select a File)(.*)$
windowrule = center on, float on, match:title ^(Choose wallpaper)(.*)$
windowrule = center on, float on, match:title ^(Open Folder)(.*)$
windowrule = center on, float on, match:title ^(Save As)(.*)$
windowrule = size (monitor_w*0.7) (monitor_h*0.6), match:title ^(Save As)$
windowrule = center on, float on, match:title ^(Library)(.*)$
windowrule = center on, float on, match:title ^(File Upload)(.*)$
windowrule = center on, float on, match:title ^(.*)(wants to save)$
windowrule = center on, float on, match:title ^(.*)(wants to open)$
windowrule = float on, size (monitor_w*0.7) (monitor_h*0.6), match:initial_title (Open Files)

windowrule = float on, fullscreen on, match:class MEGAsync
#}}} 
