# Configuration documentation is available at https://dystroy.org/broot
# internal - overrite shortcut
# todo more preview_transformers
# f keys don't work

default_flags = "--git-ignored --show-git-info"
# default_flags = "--git-ignored --show-git-info"
# enable_kitty_keyboard = false

#####################
icon_theme = "nerdfont"
# Skin
imports = [
  { luma = "dark", file = "skins/catppuccin-macchiato.hjson" },
  { luma = "light", file = "skins/white.hjson" }
]
# modal = true

# mode = "image" or "tty"
[[preview_transformers]]
input_extensions = [ "pdf" ]
output_extension = "png"
mode = "image"
command = [ "mutool", "draw", "-w", "1000", "-o", "{output-path}", "{input-path}" ]
# output_extension = "png" sixel ale broot nie obsługuje
# command = ["timg", "-p", "sixel", "-W", "--auto-crop", "--frames=1", "-g1000x500", "-o", "{output-path}", "{input-path}"]

[[preview_transformers]]
input_extensions = [ "avi","mp4","wmv","dat","3gp","ogv","mkv","mpg","mpeg","vob","m2v","mov","webm","mts","m4v","qt","divx" ]
output_extension = "png"
mode = "image"
# command = ["timg", "-U", "-p", "kitty", "--frames=1", "-g1000x500", "-o", "|", "magick",  "{output-path}", "{input-path}"]
command = ["timg", "-U", "-p", "kitty", "--frames=1", "-g1000x500", "|", "magick",  "{input-path}", "{output-path}.png" ]

[[preview_transformers]]
input_extensions = [ "7z","bz2","cab","cpio","deb","gz","msi","pkg","rar","tar","tgz","xz","zip"]
output_extension = "txt"
mode = "text"
command = [ "als", "{input-path}" ]

[[preview_transformers]]
input_extensions = [ "xls", "xlsx", "doc", "docx", "ppt", "pptx", "ods", "odt", "odp" ]
output_extension = "png"
mode = "image"
command = [ "libreoffice", "--headless", "--convert-to", "png", "--outdir", "{output-dir}", "{input-path}" ]

####################
# verbs
# files aren't open in $EDITOR 

[[verbs]]
invocation = "edit"
shortcut = "e"
key = "ctrl-e"
apply_to = "text_file"
# execution = "$EDITOR {file}"
execution = "/usr/bin/nvim {file}"
leave_broot = false

[[verbs]]
key = "ctrl-o"
shortcut = "f"
invocation = "open_stay_filter"
internal = ":open_stay_filter"

# ZSH
[[verbs]]
key = "enter"
invocation = "open"
cmd = ":write_output {directory};:quit"
apply_to = "directory"

[[verbs]]
key = "enter"
invocation = "open"
cmd = ":parent;:write_output {directory};:quit"
apply_to = "file"

  #   # https://github.com/Canop/broot/issues/530
[[verbs]]
key = "alt-enter"
external = "xdg-open {file}"
leave_broot = false
# apply_to = "file"
# [[verbs]]
# key = "alt-enter"
# invocation = "open"
# internal = ":open_stay"
# apply_to = "file"

[[verbs]]
key = "ctrl-s"
invocation = "stage_line"
cmd = ":toggle_stage;:next_match"
# [[verbs]]
# key = "ctrl-s"
# invocation = "stage_line"
# cmd = ":toggle_stage;:line_down"
[[verbs]]
key = "alt-s"
invocation = "stage_all"
internal = ":stage_all_files"
[[verbs]]
key = "ctrl-x"
invocation = "clear_stage"
internal = ":clear_stage"

## VIMLIKE
[[verbs]]
key = "ctrl-k"
invocation = "line_up"
internal = ":line_up"
[[verbs]]
key = "ctrl-j"
invocation = "line_down"
internal = ":line_down"
[[verbs]]
key = "ctrl-l"
invocation = "open_stay"
internal = ":open_stay"
[[verbs]]
key = "ctrl-h"
invocation = "parent"
internal = ":parent"
[[verbs]]
key = "ctrl-u"
invocation = "page_up"
internal = ":page_up"
[[verbs]]
key = "ctrl-d"
invocation = "page_down"
internal = ":page_down"
[[verbs]]
key = "ctrl-g"
invocation = "bottom"
internal = ":select_last"

##### Panels
[[verbs]]
key = "ctrl-v"
invocation = "panel_new"
internal = ":start_end_panel"
[[verbs]]
key = "ctrl-w"
invocation = "toggle_preview"
internal = ":toggle_preview"
#can't change to c-q
[[verbs]]
key = "ctrl-c"
invocation = "close_panel_cancel"
internal = ":close_panel_cancel"
[[verbs]]
key = "ctrl-p"
invocation = "panel_left"
internal = ":panel_left"
[[verbs]]
key = "ctrl-n"
invocation = "panel_right"
internal = ":panel_right"

# toggles
[[verbs]]
key = "ctrl-t"
invocation = "toggle_dates"
internal = ":toggle_dates"
[[verbs]]
key = "alt-t"
invocation = "toggle_tree"
internal = ":toggle_tree"
[[verbs]]
key = "ctrl-a"
invocation = "toggle_hidden"
internal = ":toggle_hidden"
# doesn't work
[[verbs]]
key = "ctrl-i"
invocation = "toggle_git_ignore"
internal = ":toggle_git_ignore"
[[verbs]]
key = "ctrl-f"
invocation = "toggle_files"
internal = ":toggle_files"
[[verbs]]
key = "F9"
invocation="toggle_perm"
internal = ":toggle_perm"
##### SORT
[[verbs]]
key = "alt-g"
internal = "toggle_sizes"
[[verbs]]
key = "F10"
invocation="sort_by_size"
internal = ":sort_by_size"
[[verbs]]
key = "F11"
invocation="sort_by_date"
internal = ":sort_by_date"
[[verbs]]
key = "F12"
invocation="sort_by_type"
internal = ":sort_by_type"

##### EXECUTION
[[verbs]]
invocation = "remove"
key = "ctrl-r"
# keys = ["ctrl-r", "delete"]
leave_broot = false
execution = "gomi {file}"
# execution = "trash-put {file}"
# or {directory} it not match dir or file it will delete parrent!
# execution = "rm -rf {file}"
[[verbs]]
key = "F1"
invocation = "refresh"
internal = ":refresh"
[[verbs]]
key = "F5"
invocation = "copy_to_panel"
execution = "cp -r {file} {other-panel-directory}"
leave_broot = false
# internal = ":cpp" can't be overrited 
[[verbs]]
name = "move"
key = "F6"
invocation = "move_to_panel"
execution = "mv {file} {other-panel-directory}"
leave_broot = false
# internal = ":move_to_panel" can't be overrited 
[[verbs]]
name = "mkdir"
key = "F7"
invocation = "mkdir {new_dir}"
execution = "/bin/mkdir -p {directory}/{new_dir}"
leave_broot = false
auto_exec = false
# execution = "mkdir -p {subpath:path-from-directory}"
[[verbs]]
name = "touch"
key = "F8"
invocation = "touch {new_file}"
execution = "touch {directory}/{new_file}"
leave_broot = false
auto_exec = false

# todo - probably I have different difftool than meld
[[verbs]]
invocation = "diff"
external = "git difftool -y {file}"
leave_broot = false

# BOOKMARKS
[[verbs]]
invocation = "home"
key = "alt-h"
internal = ":focus ~/"

# If $PAGER isn't set on your computer, you should either set it
#  or just replace it with your viewer of choice in the 'execution'
#  pattern.
# Example:
#  execution = "less {file}"
# execution = "$PAGER {file}"


